name: NASA Project CI
on:
  push:
         branches: [main]
  pull_request:
          branches: [main]      
jobs:
 build:
    runs-on: ubuntu-latest
    steps:  
        -uses: action/checkout@v2
        -name: Use Node.Js Version 20         
          uses: action/setup-node@v2   
          with: 
             node-version : "20"
        -run: npm install 
        -run: npm run build --prefix client
                       
